#!/usr/bin/env bash
set -euo pipefail

# Runs a matrix of workloads generated by generate_workload_configs.py
# Usage:
#   ./run_workload_matrix.sh <edge_devices_file> <applications_file> [num_runs]
#
# Example:
#   ./run_workload_matrix.sh edge_ai_devices_scaled.xml applications_dag_stable_diffusion.xml 1

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="${SCRIPT_DIR}/config"

EDGE_DEVICES_FILE="${1:-edge_ai_devices_scaled.xml}"
APPLICATIONS_FILE="${2:-applications_dag_stable_diffusion.xml}"
NUM_RUNS="${3:-1}"

if ! [[ "${NUM_RUNS}" =~ ^[0-9]+$ ]] || [[ "${NUM_RUNS}" -lt 1 ]]; then
  echo "NUM_RUNS must be a positive integer"
  exit 1
fi

# Generate configs if missing
if ! ls "${CONFIG_DIR}"/DAG_APP_W*_REMOTE_RL.properties >/dev/null 2>&1; then
  python3 "${SCRIPT_DIR}/generate_workload_configs.py"
fi

for props in "${CONFIG_DIR}"/DAG_APP_W*_REMOTE_RL.properties "${CONFIG_DIR}"/DAG_APP_W*_GLOBAL_BEST_FIT.properties; do
  [ -f "${props}" ] || continue
  scenario_name="$(basename "${props}" .properties)"
  echo "=== Running ${scenario_name} ==="
  "${SCRIPT_DIR}/run_config_batch.sh" "${scenario_name}" "${EDGE_DEVICES_FILE}" "${APPLICATIONS_FILE}" "${NUM_RUNS}"
done
