#!/usr/bin/env bash
set -euo pipefail

# Runs a matrix of workloads generated by generate_workload_configs.py
# Usage:
#   ./run_workload_matrix.sh <edge_devices_file> <applications_file> [num_runs]
#
# Example:
#   ./run_workload_matrix.sh edge_ai_devices_scaled.xml applications_dag_stable_diffusion.xml 1

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="${SCRIPT_DIR}/config"

EDGE_DEVICES_FILE="${1:-edge_ai_devices_scaled.xml}"
APPLICATIONS_FILE="${2:-applications_dag_stable_diffusion.xml}"
NUM_RUNS="${3:-1}"

if ! [[ "${NUM_RUNS}" =~ ^[0-9]+$ ]] || [[ "${NUM_RUNS}" -lt 1 ]]; then
  echo "NUM_RUNS must be a positive integer"
  exit 1
fi

# Generate configs if missing
if [ ! -f "${SCRIPT_DIR}/workload_matrix.csv" ]; then
  python3 "${SCRIPT_DIR}/generate_workload_configs.py"
fi

while IFS=, read -r scenario edge_xml app_xml policy workload capacity vm_type; do
  if [ "${scenario}" = "scenario" ]; then
    continue
  fi
  edge_file="${edge_xml:-${EDGE_DEVICES_FILE}}"
  app_file="${app_xml:-${APPLICATIONS_FILE}}"
  echo "=== Running ${scenario} (${policy}, ${workload}, ${capacity}, ${vm_type}) ==="
  "${SCRIPT_DIR}/run_config_batch.sh" "${scenario}" "${edge_file}" "${app_file}" "${NUM_RUNS}"
done < "${SCRIPT_DIR}/workload_matrix.csv"
